# Generated by Django 2.2.7 on 2021-06-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Name', models.CharField(max_length=30, verbose_name='Class')),
            ],
            options={
                'db_table': 'classes_master',
            },
        ),
        migrations.CreateModel(
            name='Section_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_Name', models.CharField(max_length=30, verbose_name='Section')),
            ],
            options={
                'db_table': 'section_master',
            },
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Academic_Session', models.CharField(choices=[('-', 'Select'), ('2019-2020', '2019-2020'), ('2000-2021', '2000-2021'), ('2021-2022', '2021-2022')], max_length=50, null=True, verbose_name='Academic Session')),
                ('Stud_class', models.CharField(choices=[('5', 'Select'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th')], max_length=50, null=True, verbose_name='Student Class')),
                ('Section', models.CharField(choices=[('1', 'Select'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50, null=True, verbose_name='Student Section')),
                ('Roll_no', models.IntegerField(verbose_name='Roll No')),
                ('Student_name', models.CharField(max_length=100, verbose_name='Student`s Name')),
                ('Father_name', models.CharField(max_length=100, verbose_name='Father`s Name')),
                ('Mother_name', models.CharField(max_length=100, verbose_name='Mother`s Name')),
                ('Date_of_Birth', models.DateField()),
                ('Subject_English', models.CharField(default='English', max_length=10, verbose_name='English')),
                ('English_p_test_term1', models.IntegerField(default='', verbose_name='English_p_test_term1')),
                ('English_Note_Book_term1', models.IntegerField(verbose_name='English_Note_Book_term1')),
                ('English_Sub_Enrichment_term1', models.IntegerField(verbose_name='English_Sub_Enrichment_term1')),
                ('English_Half_Yearly_Exam_term1', models.IntegerField(verbose_name='English_Half_Yearly_Exam_term1')),
                ('English_Marks_obtained_term1', models.IntegerField(verbose_name='English_Marks_obtained_term1')),
                ('English_Grade_term1', models.CharField(max_length=10, verbose_name='English_Grade_term1')),
                ('English_p_test_term2', models.IntegerField(verbose_name='English_p_test_term2')),
                ('English_Note_Book_term2', models.IntegerField(verbose_name='English_Note_Book_term2')),
                ('English_Sub_Enrichment_term2', models.IntegerField(verbose_name='English_Sub_Enrichment_term2')),
                ('English_Half_Yearly_Exam_term2', models.IntegerField(verbose_name='English_Half_Yearly_Exam_term2')),
                ('English_Marks_obtained_term2', models.IntegerField(verbose_name='English_Marks_obtained_term2')),
                ('English_Grade_term2', models.CharField(max_length=10, verbose_name='English_Grade_term2')),
                ('Subject_Hindi', models.CharField(default='Hindi', max_length=10, verbose_name='Hindi')),
                ('Hindi_p_test_term1', models.IntegerField(default='', verbose_name='Hindi_p_test_term1')),
                ('Hindi_Note_Book_term1', models.IntegerField(verbose_name='Hindi_Note_Book_term1')),
                ('Hindi_Sub_Enrichment_term1', models.IntegerField(verbose_name='Hindi_Sub_Enrichment_term1')),
                ('Hindi_Half_Yearly_Exam_term1', models.IntegerField(verbose_name='Hindi_Half_Yearly_Exam_term1')),
                ('Hindi_Marks_obtained_term1', models.IntegerField(verbose_name='Hindi_Marks_obtained_term1')),
                ('Hindi_Grade_term1', models.CharField(max_length=10, verbose_name='Hindi_Grade_term1')),
                ('Hindi_p_test_term2', models.IntegerField(default='', verbose_name='Hindi_p_test_term2')),
                ('Hindi_Note_Book_term2', models.IntegerField(verbose_name='Hindi_Note_Book_term2')),
                ('Hindi_Sub_Enrichment_term2', models.IntegerField(verbose_name='Hindi_Sub_Enrichment_term2')),
                ('Hindi_Half_Yearly_Exam_term2', models.IntegerField(verbose_name='Hindi_Half_Yearly_Exam_term2')),
                ('Hindi_Marks_obtained_term2', models.IntegerField(verbose_name='Hindi_Marks_obtained_term2')),
                ('Hindi_Grade_term2', models.CharField(max_length=10, verbose_name='Hindi_Grade_term2')),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
