# Generated by Django 2.2.7 on 2021-07-21 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='IT_Enrichment_term2',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='IT_Enrichment_term2'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='IT_Grade_term2',
            field=models.CharField(default=0, max_length=10, null=True, verbose_name='IT_Grade_term2'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='IT_Half_Yearly_Exam_term2',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='IT_Half_Yearly_Exam_term2'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='IT_Marks_obtained_term2',
            field=models.IntegerField(default=0, null=True, verbose_name='IT_Marks_obtained_term2'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='IT_Note_Book_term2',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='IT_Note_Book_term2'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='IT_p_test_term2',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='IT_p_test_term2'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='Subject_IT',
            field=models.CharField(default='IT', max_length=10, verbose_name='IT'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Academic_Session',
            field=models.CharField(choices=[('-', 'Select'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022')], default='2000-2021', max_length=50, verbose_name='Academic Session'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Father_name',
            field=models.CharField(max_length=100, verbose_name='Father`s Name'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Mother_name',
            field=models.CharField(max_length=100, verbose_name='Mother`s Name'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Roll_no',
            field=models.IntegerField(verbose_name='Roll No'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Student_name',
            field=models.CharField(max_length=100, verbose_name='Student`s Name'),
        ),
    ]
