# Generated by Django 2.2.7 on 2021-06-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Grade_term1',
            field=models.CharField(default=0, max_length=10, verbose_name='Marathi_Grade_term1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Grade_term2',
            field=models.CharField(default=0, max_length=10, verbose_name='Marathi_Grade_term2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Half_Yearly_Exam_term1',
            field=models.IntegerField(default=0, verbose_name='Marathi_Half_Yearly_Exam_term1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Half_Yearly_Exam_term2',
            field=models.IntegerField(default=0, verbose_name='Marathi_Half_Yearly_Exam_term2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Marks_obtained_term1',
            field=models.IntegerField(default=0, verbose_name='Marathi_Marks_obtained_term1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Marks_obtained_term2',
            field=models.IntegerField(default=0, verbose_name='Marathi_Marks_obtained_term2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Note_Book_term1',
            field=models.IntegerField(default=0, verbose_name='Marathi_Note_Book_term1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Note_Book_term2',
            field=models.IntegerField(default=0, verbose_name='Marathi_Note_Book_term2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Sub_Enrichment_term1',
            field=models.IntegerField(default=0, verbose_name='Marathi_Sub_Enrichment_term1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_Sub_Enrichment_term2',
            field=models.IntegerField(default=0, verbose_name='Marathi_Sub_Enrichment_term2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_p_test_term1',
            field=models.IntegerField(default='', verbose_name='Marathi_p_test_term1'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='Marathi_p_test_term2',
            field=models.IntegerField(default='', verbose_name='Marathi_p_test_term2'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='Subject_Marathi',
            field=models.CharField(default='Marathi', max_length=10, verbose_name='Marathi'),
        ),
    ]
