# Generated by Django 2.2.7 on 2021-07-21 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_auto_20210721_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='IT_Enrichment_term2',
        ),
        migrations.AddField(
            model_name='student_details',
            name='IT_Sub_Enrichment_term2',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='IT_Sub_Enrichment_term2'),
        ),
    ]
